### ISSUE TITLE
Does not work for dynamic items

### ISSUE THREAD

**Issue by JamesArthurHolland** [JSmith01/vue-selectable#3]
When I use static items, such as the array ['abc', 'bcd', 'cde'] in the example, it works fine.

When I use a dynamic bind, such as 

    v-for='(contact, i) in getContacts()'

    ...

    getContacts() { 
        return this.$store.getters.allContacts; 
    },

It does not work?

**Comment by JSmith01** [comment]
Yes, this is known behavior. Directive relies on real browser's DOM and that's why it needs to be informed on DOM updates performed by Vue.js framework.

For internal use I'm doing update using `setSelectableItems()` after every change on dynamic list. So if you have function that returns promise, then you can do in component (I'm using `fetch` only to illustrate idea):
```js
loadDataToList() {
  fetch('/some/data/url').then(result => result.json()).then(data => { this.data = data; })
    .then(() => this.$nextTick(() => setSelectableItems(this.$refs.selectableTable)));
}
```
Please note this requires `ref="selectableTable"` on selectable container element. You can also do this trick via vue.js `watchers` functionality.

Another thing I have to mention is that if you have some filtering/search functionality in your app, then to be more efficient you have to use `v-show` instead of `v-if` since first one doesn't modify DOM.

**Comment by JSmith01** [comment]
Please check `examples2/example4.html` - it has to answer your question.

Please also remember that if you want to leave selection on DOM update - you have to do it manually in your code that handles list changes.
